export { default as UserAsAlien } from './UserAsAlien';
export { default as UserAsDevil } from './UserAsDevil';
export { default as UserAsDragon } from './UserAsDragon';
export { default as UserAsRobot } from './UserAsRobot';
export { default as UserBasic } from './UserBasic';
export { default as UserFeelGlad } from './UserFeelGlad';
export { default as UserFeelHappy } from './UserFeelHappy';
export { default as UserFeelNeutral } from './UserFeelNeutral';
export { default as UserFeelSad } from './UserFeelSad';
